### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Lootyhoof** [ThosRTanner/tabgroupsmanager#26]
I notice there are two different licenses on this add-on: MPL 2.0 and the contents of [license.txt](https://github.com/ThosRTanner/tabgroupsmanager/blob/master/license.txt) (translated below):

````
There is no warranty for this add-on.
This add-on is free to use for both commercial and non-commercial purposes.
If you don't change the content at all, you are free to redistribute it.
Modification or diversion of the source is prohibited at this time.
However, you are not limited to using a piece of code when overriding from another add-on.
If so, provide a setting that allows the user to override that override.
---
That's all for the license terms.
I could not upload to Firefox add-ons without a license, so I made it in a hurry.
As for code modification, we may make a firm rule over time or choose another license.
However, I cannot select a license whose original text is in English and whose court of jurisdiction is not Japan, so there is no license available at the moment.
````
The original developer looked to [disappear](https://discourse.mozilla.org/t/development-and-maintenance-of-tabgroupsmanager-extension/5935) many years ago so others took it anyway and it hasn't been disputed, so that isn't much of a concern. Though if this really is now MPL2.0 you should remove that license too.

**Comment by ThosRTanner** [comment]
Ah. I shall remove the older one then. I couldn't read it and left it lying around. Thanks
