### ISSUE TITLE
TGM menu stopped showing up after a few days

### ISSUE THREAD

**Issue by michaelshiloh** [ThosRTanner/tabgroupsmanager#35]
First of all, thanks a million for working on this invaluable extension. I hope this is the right place to report a problem; if not, please tell me what I should do instead and I apologize for my ignorance:

Installed TGM on Basilisk. Opened tabs, created groups, hibernated groups, woke up. All seemed good.

After a few days I don't get the TGM items in the menu when I right click on a tab. I see the usual Firefox items, but not the all important "move tab to group" option.

My groups are still present, I can wake them up, hibernate them, and rename them, but I can't move tabs into groups.

Any suggestions?

**Comment by ThosRTanner** [comment]
That's odd. By 'after a few days', do you mean 'after the browser has been up for a few days', because I have never tried that. Or is that 'after a few days worth of restarts'? 

If you bring up the browser console (ctrl-shift-J) do you see anything when you right click the tab? And what other extensions are you running? Did you add a new one recently?

If you restart the browser, do things start working again?

**Comment by michaelshiloh** [comment]
Thanks for your reply.
1. After a few days of no restarts
2. Yes, lots. I'll paste it below
3. No other extensions
4. Restarting browser does not help
happy to run other tests - let me know
busy  
Session.js:72:5
start waiting 0 21  
Session.js:82:5
unexpected group? -1   
Session.js:159:5
complete 0  
Session.js:98:5
unreachable code after return statement[Learn More]  
app.28a86c90d20ffcb7a7cc.js:1:1034134
unreachable code after return statement[Learn More]  
d2826.js:1:53888
unreachable code after return statement[Learn More]  
d2826.js:1:54130
unreachable code after return statement[Learn More]  
d2826.js:1:54369
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!  
duckduckgo.com
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.  
l118.js:26:45625
Key event not available on some keyboard layouts: key=“r” modifiers=“accel,alt” id=“key_toggleReaderMode”  
browser.xul
Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox”  
browser.xul
Use of Mutation Events is deprecated. Use MutationObserver instead.  
m=sm:433:32
Empty string passed to getElementById().  
m=b:1062:249
The character encoding of a framed document was not declared. The document may appear different if viewed without the document framing it.  
hscv
Attempt to set a forbidden header was denied: Connection  
1986475897-lcs_client_bin.js:123:386
NetworkError: Failed to load worker script at https://github.githubassets.com/assets/socket-worker-76329a4d.js (nsresult = 0x805e0006)  
socket-worker.js:1
Attempt to set a forbidden header was denied: Connection  
1986475897-lcs_client_bin.js:123:386
busy  
Session.js:72:5
start waiting 0 23  
Session.js:82:5
A call to document.write() from an asynchronously-loaded external script was ignored.  
conversion.js:63:243
v1.0  
script.js:2:1
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead[Learn More]  
jquery.js:1
scout-to-render: timer started
bvapi.js:1
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.  
jquery.js:3:31293
Use of getAttributeNode() is deprecated. Use getAttribute() instead.  
jquery.js:4:29041
8220-12vmax-high-performance-cordless  
8220-12vmax-high-performance-cordless:3885:7
All portlets are ready  
main.js:1:107
scout-to-render: 5434ms
bv-primary.js:74
Success  
8220-12vmax-high-performance-cordless:3900:27
Use of attributes’ nodeValue attribute is deprecated. Use value instead.  
CLPlayer.core.min.js:18:207309
TypeError: this.popupGroup is null[Learn More]  
GroupMenu.js:14:3
Attempt to set a forbidden header was denied: Connection  
1986475897-lcs_client_bin.js:123:386
NetworkError: Failed to load worker script at https://github.githubassets.com/assets/socket-worker-76329a4d.js (nsresult = 0x805e0006)  
socket-worker.js:1
Firefox can’t establish a connection to the server at wss://web.whatsapp.com/ws.  
app.28a86c90d20ffcb7a7cc.js:1:843054
Attempt to set a forbidden header was denied: Connection  
1986475897-lcs_client_bin.js:123:386
The connection to wss://web.whatsapp.com/ws was interrupted while the page was loading.  
app.28a86c90d20ffcb7a7cc.js:1:843054
Attempt to set a forbidden header was denied: Connection  
1986475897-lcs_client_bin.js:123:386
NetworkError: Failed to load worker script at https://github.githubassets.com/assets/socket-worker-76329a4d.js (nsresult = 0x805e0006)  
socket-worker.js:1
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!  
35
Attempt to set a forbidden header was denied: Connection  
1986475897-lcs_client_bin.js:123:386
POST 
XHR 
https://play.google.com/log [HTTP/2.0 200 OK 315ms]
GET 
https://ssl.gstatic.com/ui/v1/icons/mail/images/cleardot.gif [HTTP/2.0 200 OK 240ms]
GET 
https://translate.google.com/_/TranslateCommunityUi/gen204/ [HTTP/2.0 204 No Content 429ms]
GET 
https://ssl.gstatic.com/ui/v1/icons/mail/images/cleardot.gif [HTTP/2.0 200 OK 147ms]
POST 
XHR 
https://play.google.com/log [HTTP/2.0 200 OK 244ms]
GET 
https://ssl.gstatic.com/ui/v1/icons/mail/images/cleardot.gif [HTTP/2.0 200 OK 200ms]
Attempt to set a forbidden header was denied: Connection  
1986475897-lcs_client_bin.js:123:386
GET 
XHR 
https://0.client-channel.google.com/client-channel/channel/bind [HTTP/2.0 200 OK]
GET 
https://translate.google.com/_/TranslateCommunityUi/gen204/ [HTTP/2.0 204 No Content 169ms]
POST 
XHR 
https://play.google.com/log [HTTP/2.0 200 OK 154ms]

Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.  
(unknown)
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.  
(unknown)
Content Security Policy: Ignoring “'unsafe-inline'” within script-src or style-src: nonce-source or hash-source specified  
(unknown)
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified  
(unknown)
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified  
(unknown)
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified  
(unknown)
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src 'nonce-Qa8knUf6ahWFvn+rZoDHzg' 'unsafe-inline' 'strict-dynamic' https: http: 'unsafe-eval'”). Source: onsubmit attribute on INPUT element.  
1
Content Security Policy: The page’s settings blocked the loading of a resource at https://github.githubassets.com/assets/socket-worker-76329a4d.js (“worker-src https://github.com/socket-worker.js https://gist.github.com/socket-worker.js”).  
(unknown)

**Comment by ThosRTanner** [comment]
Well, this:

TypeError: this.popupGroup is null[Learn More]
GroupMenu.js:14:3

Looks like it's related. Not much of the other stuff though.

Not sure I can replicate 'browser has been up for a few days'. I'll have to see if I can replicate this myself or find a way of triggering it.

**Comment by michaelshiloh** [comment]
I'm happy to run code with more debugging hooks or something like that. Let
me know.

**Comment by ThosRTanner** [comment]
Also, could you provide a list of other extensions you are using. And how many windows and tabs you have open?

I might end up having to resort to asking you for your session data files as well, but I'll see if I can avoid that.

**Comment by michaelshiloh** [comment]
I have:

   -  zero other extensions
   - Only 1 window
   - 20 tabs in my main group
   - 2 tabs in another group
   - 6 groups hibernating, each with only 1-3 tabs

**Comment by michaelshiloh** [comment]
Update:

I have tried disabling/re-enabling the extension, and
uninstalling/reinstalling, but alas neither helped.

**Comment by michaelshiloh** [comment]
Interestingly, the TGM menu does show up on the groups: I can hibernate and
suspend groups, rename, etc.

**Comment by michaelshiloh** [comment]
Another update: I have found a workaround!


   1. I can open the group menu by hovering over the group bar and
   right-click. This allows me to create a new group
   2. I can move tabs into groups by dragging them.

This workaround allows me to move tabs to new groups.

**Comment by ThosRTanner** [comment]
Glad you've got a workround at least. I'm still befuddled as to why the 'add to new group' menu is failing to appear on right click in a tab. Time to create another blank profile in basilisk and try that. It (TGM) hooks off the tab menu with some scary xul stuff which I suspect is what is going wrong, but its not obvious how yet.

**Comment by ThosRTanner** [comment]
This question might sound a bit odd. If you create a new widow, does the menu appear when right clicking a tab in that window?

Also, I don't know how your editing is, but if you could find chrome\content\TabContextMenu.js in the extension folder, and add this:

    console.log("menu is", menu);

just after the line

  let menu = gBrowser.tabContextMenu;

at around line 25. That should print something in the log,

**Comment by michaelshiloh** [comment]
>> This question might sound a bit odd. If you create a new widow, does the
menu appear when right clicking a tab in that window?

No

>> find chrome\content\TabContextMenu.js in the extension folder, and add
this

Done! Now what?

**Comment by ThosRTanner** [comment]
when you restart the browser (and every time you create a new window subsequent to that), you should get something in the browser log saying "menu is" + a lot of stuff. Could you paste it here. Thanks

**Comment by michaelshiloh** [comment]
Where is my browser log?

**Comment by michaelshiloh** [comment]
Is it this:

busy
Session.js:72:5
start waiting 0 37
Session.js:82:5
no group??? undefined
Session.js:139:5
complete 0
Session.js:98:5
Use of Mutation Events is deprecated. Use MutationObserver instead.
m=sm:342:32
The character encoding of a framed document was not declared. The document
may appear different if viewed without the document framing it.
hscv
The character encoding of a framed document was not declared. The document
may appear different if viewed without the document framing it.
hscv
Attempt to set a forbidden header was denied: Connection
1986475897-lcs_client_bin.js:123:386
This site appears to use a scroll-linked positioning effect. This may not
work well with asynchronous panning; see
https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects
for further details and to join the discussion on related tools and
features!
1
Key event not available on some keyboard layouts: key=“r”
modifiers=“accel,alt” id=“key_toggleReaderMode”
browser.xul
Key event not available on some keyboard layouts: key=“i”
modifiers=“accel,alt,shift” id=“key_browserToolbox”
browser.xul
Empty string passed to getElementById().
m=b:1062:249
Attempt to set a forbidden header was denied: Connection
1986475897-lcs_client_bin.js:123:386
Empty string passed to getElementById().
m=b:1062:249
POST
XHR
https://mail.google.com/sync/u/1/i/fd [HTTP/2.0 200 OK 322ms]
POST
XHR
https://play.google.com/log [HTTP/2.0 200 OK 119ms]
OPTIONS
XHR
https://people-pa.clients6.google.com/v2/people/lookup [HTTP/2.0 200 OK
126ms]
GET
XHR
https://people-pa.clients6.google.com/v2/people/lookup [HTTP/2.0 200 OK
301ms]
OPTIONS
XHR
https://people-pa.clients6.google.com/v2/people/lookup [HTTP/2.0 200 OK
123ms]
GET
XHR
https://people-pa.clients6.google.com/v2/people/lookup [HTTP/2.0 200 OK
189ms]

**Comment by ThosRTanner** [comment]
Yes, from the window you get with ctrl-shift-J or Tools->Web Developer->Browser Console. It should have a line starting with 'menu is'. It should come out before the line that says busy. At least, it should when you restart the browser.

**Comment by ThosRTanner** [comment]
Oh. I'm feeling incredibly dim. Can you check your preferences. Go to the addons page (ctrl-shift-A), select Extensions to get the list of your installed extensions, there's an entry for Tab Groups Manager - click the Options button. This will get you a 'TabGroups Manager Preferences' wndow. Click Menu, and then 'Tab Context Menu'.  Make sure 'Send to other group' is checked and press OK.

**Comment by michaelshiloh** [comment]
You're not dim, that's not the problem. All of the items in that list are
checked yet none of them show up.

**Comment by michaelshiloh** [comment]
Here's something strange. I opened a new window and I did get the "create
new group" option. Then I opened another new window and didn't. So I shut
down Basilisk and started again and still no "create new group" option.

**Comment by michaelshiloh** [comment]
And here is the log after shutting down basilisk and opening it up with
just one group called "test":

GET
XHR
http://detectportal.palemoon.org/success.txt [HTTP/1.1 200 OK 442ms]
unexpected group? 14 test
Session.js:159:5
Webconsole context has changed
GET
https://mail.google.com/mail/u/1/#inbox/FMfcgxwJWrdtzPDNDBvGXRngWZdfqbrT
[1ms]

**Comment by ThosRTanner** [comment]
and you get no trace in the browser log saying "menu is"? It sounds like the initialisation is failing in a very odd way

**Comment by michaelshiloh** [comment]
I copied the entire log to you.

One thing I noticed is when I open the browser console there are multiple
tabs, and they seem to highlight different portions of the screen but I
couldn't quite figure it out. Is it possible I have the wrong tabs selected?

**Comment by michaelshiloh** [comment]
Or possibly what you said about initialization. Can we add some debug
messages earlier in the process? I'm happy to edit code.

**Comment by ThosRTanner** [comment]
Not entirely sure where github put the log!

There's a whole row of buttons on the the browser console. if you click net, css, security and server so they are off (not highlighted) and JS and Logging are on (highlighted), you should get the important messages.

Thinking if some debugging trace to add

**Comment by michaelshiloh** [comment]
I did what you said and now I get this:

busy   Session.js:72:5
start waiting 0 18   Session.js:82:5
no group??? undefined   Session.js:139:5
complete 0   Session.js:98:5

**Comment by ThosRTanner** [comment]
OK. So, in chrome\content\TabGroupsManager.js 

at around line 130, you'll see

        if (TabGroupsManagerJsm.globalPreferences.prefService.getIntPref("browser.startup.page") < 3) setTimeout(function ()

add this line before

    console.log(TabGroupsManagerJsm.globalPreferences.prefService.getIntPref("browser.startup.page"));

at around line 160, you'll see

      this.tabContextMenu.makeMenu();

Replace this with

      try
      {
        console.log("make menu");
        this.tabContextMenu.makeMenu();
        console.log("make menu done");
      }
      catch (e)
      {
        console.log("error", e);
      }

hopefully that will put something useful to the console

**Comment by ThosRTanner** [comment]
Ah ha! I have reproduced this. You have your startup preference to 'Show my windows and tabs from last time', yes?

In chrome\content\TabGroupsManager.js,  at line 130, replace

    if (TabGroupsManagerJsm.globalPreferences.prefService.getIntPref("browser.startup.page") < 3) setTimeout(function ()

with

    setTimeout(function ()

and that should fix your problem

**Comment by michaelshiloh** [comment]
Indeed, I do have my startup preference to 'Show my windows and tabs from
last time'!

I implemented the change you suggested and it fixed my problem!

You, sir, are brilliant!!! A million thanks!!!!

Michael
