### ISSUE TITLE
Tab group manager make window control buttons invisible if the window is maximized in foreground

### ISSUE THREAD

**Issue by badnick1** [ThosRTanner/tabgroupsmanager#51]
The issue started with 30.0.0 Pale Moon vesio
<img width="960" alt="Screenshot (1366)" src="https://user-images.githubusercontent.com/32221948/159052696-8001ae19-1313-438d-9a1e-3b0a618a810a.png">
n

**Comment by ThosRTanner** [comment]
How do you get the title bar to disappear like that? I don't have this and even after creating a new blank profile, I still don't have that.  I have a separate navigation bar and title bar

**Comment by badnick1** [comment]
> How do you get the title bar to disappear like that? I don't have this and even after creating a new blank profile, I still don't have that. I have a separate navigation bar and title bar

Yeah, sorry, I had set "tab on top" for Pale Moon but for that, I should set"Ordinal for Groupbar" to 0 in TGM settings, otherwise TGM is not working well when "tab on top " is enabled. Strange but before 30.0.0 version,  worked without setting "Ordinal for Groupbar" to 0. And in fact the buttons are not really vanished, just became white colored wich is not in contrast with my Windows personalization.

**Comment by ThosRTanner** [comment]
urg. not sure what I can do about the buttons colours. I'll have a look. Which buttons are these?

**Comment by badnick1** [comment]
> urg. not sure what I can do about the buttons colours

I think is nothing to do because now is working ( after I set "Ordinal for Groupbar" to 0 ), now I have contrast color and the buttons are visible.
<img width="960" alt="Screenshot (1368)" src="https://user-images.githubusercontent.com/32221948/159163013-3225b76c-0470-421b-aa2b-31b495d2926b.png">

**Comment by ThosRTanner** [comment]
yay!
